### ISSUE TITLE
Following readme instructions, but I am still not getting pull requests for classic hook

### ISSUE THREAD

**Issue by radrad** [1egoman/backstroke#46]
I have a fork of user1/repo1/ (for I am not the ownor or contributor) in my user/repo1 repository. 
Within my user/repo1 repositor I created a classic backstroke hook in the Settings... Webhooks Payload URL =  http://backstroke.us/ .

When  a new commit comes I am not receiving any new pull requests because there is an error during a Recent Delivery in web hook log:
{
	"message" : "Validation Failed",
	"errors" : [{
			"resource" : "PullRequest",
			"code" : "custom",
			"field" : "fork_collab",
			"message" : "fork_collab Fork collab can't be granted by someone without permission"
		}
	],
	"documentation_url" : "https://developer.github.com/v3/pulls/#create-a-pull-request"
}

Based on instruction in readme page it should work.
Am I missing something?

**Comment by 1egoman** [comment]
@radrad You're doing everything right. This is definitely a bug.

I'm looking into this. I am able to reproduce the error, and it looks like something that changed within Github's API. That error message you're seeing is coming directly from Github, but I can't find documentation on it anywhere.

By any chance, is either the upstream of the fork a private repository? Currently, private repositories don't work with Backstroke.

Thanks for reporting the issue!

**Comment by radrad** [comment]
Source repo is public: https://github.com/radrad1/DevOpsWorkRadGit.
Destination (forked) i also public: https://github.com/radrad1/DevOpsWorkRadGit

This is just a test. I am the owner of both Github accounts (different emails) so I can push some commits to my source repo and see it as a pull request.
My goal is totally sync the two without my intervention. My goal is to use Visual Studio team services to do a Continuous Integration based on any commits (successful pull merge requests on my fork) in Azure so I can do automatic deployment since I am not the owner of the repository. If I was this sync wouldn't be necessary and I could have a CI builds happening because of the ownership of the repository. 

The actual repo I am after is https://github.com/VirtoCommerce/ which I need to build whenever any contributor commits any changes. 
Let me know if you can fork https://github.com/radrad1/DevOpsWorkRadGit repo and I can do a few test commits to replicate the problem.
Rad

**Comment by 1egoman** [comment]
@radrad Thanks for your help. This to me seems like a github-level issue, and I've submitted a support ticket for assistance. It's reproduced below for posterity.


Hello,

I'm working on fixing an issue in one of [my projects](https://github.com/1egoman/backstroke) and I'm running across an error I cannot find any documentation for online. The below curl (to my understanding) should create a pull request on `1egoman/bluebird`, branch `master` with `petkaantonov/bluebird`, branch `master` at the head (If the pull request was accepted, the changes in `petkaantonov/bluebird` would be merged into `1egoman/bluebird`).

```
curl -X POST -H 'Authorization: token REDACTED' -H 'Content-Type: application/json' -d '{"title": "foo", "head": "petkaantonov:master", "base": "master"}' https://api.github.com/repos/1egoman/bluebird/pulls
```

Here's what I get instead:
```
$ curl -X POST -H 'Authorization: token REDACTED' -H 'Content-Type: application/json' -d '{"title": "foo", "head": "petkaantonov:master", "base": "master"}' https://api.github.com/repos/1egoman/bluebird/pulls -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.30.253.117...
* TCP_NODELAY set
* Connected to api.github.com (192.30.253.117) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> POST /repos/1egoman/bluebird/pulls HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: token REDACTED
> Content-Type: application/json
> Content-Length: 65
> 
* upload completely sent off: 65 out of 65 bytes
< HTTP/1.1 422 Unprocessable Entity
< Server: GitHub.com
< Date: Fri, 13 Jan 2017 12:17:53 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 332
< Status: 422 Unprocessable Entity
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4988
< X-RateLimit-Reset: 1484312510
< X-OAuth-Scopes: public_repo
< X-Accepted-OAuth-Scopes: 
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-GitHub-Request-Id: AC61607A:2E856:562B98:5878C571
< 
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "code": "custom",
      "field": "fork_collab",
      "message": "fork_collab Fork collab can't be granted by someone without permission"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
* Curl_http_done: called premature == 0
* Connection #0 to host api.github.com left intact
```

I cannot find any information about `fork_collab` online as it relates to the Github API, could you provide some context?

Thanks,
Ryan

**Comment by 1egoman** [comment]
@radrad 
After some digging (and a support response), I found out that this is partially Github's fault and partially the fault of `node-github` (the github api client this project uses).

My support response:

```
Hey Ryan,

Thanks so much for reaching out and reporting this. I might have an idea about why that's happening -- it might be related to the maintainer_can_modify parameter documented here:

https://developer.github.com/v3/pulls/#create-a-pull-request

By default, that parameter is set to true to match the behavior in the UI. However, in this specific case, you're creating a pull request from a branch you don't have push access to, correct? As a result, you aren't allowed to grant push access to the head branch. Because you aren't allowed to grant that access and because of the default value for the maintainer_can_modify parameter -- the call fails.

Can you try passing in the maintainer_can_modify parameter in the call as well, and set it to false, and see if that helps? If it does, then I think we can confirm this was the problem and I can open an issue internally to ask the team to improve this behavior (by providing a more helpful error message, for example).

Best,
Ivan
```

Issue in `node-github` that addresses this problem: https://github.com/mikedeboer/node-github/issues/490
PR that fixes the problem in `node-github`: https://github.com/mikedeboer/node-github/pull/491

Once the above has been merged and a new release has been made, I've confirmed the above changes fix backstroke. Unfortunately, there isn't much I can do until then.

Thanks for your patience,
Ryan

**Comment by radrad** [comment]
Ok. The meaning of of this parameter is not clear to me. Why would it be false?
I was trying to set Payload URL to http://webhook.site/ randomly generated URL address to see what is being posted for "push" event or even "everything" Somehow I can only get a ping request and nothing else. I am only getting some posts if I manually do pull request and Merge pull request afterwords. 

I am trying to do something you are doing and even more. To automatically merge pull request. My goal is to have my forked repo auto sync with the upstream repo branch so I can trigger my Continuous Build based on commits. I would like to preserve all the history of the forked branch. 

Should I use "Rebase and Merge" instead of "Create a merge commit" to accomplish clear history of upstream repository branch. I would like to have exactly the same history of commits (excluding merge commit. Is it possible). or maybe do something like here:
https://walkingthestack.blogspot.com/2012/05/why-you-should-use-git-merge-no-ff-when.html
So what would be normal git commands to accomplish full synchronization between original and forked repo. This would of course require the code to be downloaded on you client machine, merged and pushed back to github. I would like to archive this via Rest api on the ghithub server itself

Can you paste here what you are getting in backstroke.us code behind when one sets
http://backstroke.us as the payload url on his forked repo and push event or everything.
What response are you suppose to send to github? Any requred response? And are you making a synchronous call to github POST /repos/:owner/:repo/pulls to create a pull request. 
Is there a way to do "Create a merge commit" via rest api afterwords avoiding manual merge? 

Can we meet online so we can discuss how to accomplish this. My email is radoslav A t everest kc dot net.
Can you post here a message when you updated the code behind backstroke.us so I can test it?

Thanks,

**Comment by 1egoman** [comment]
Merged in #47 to hopefully fix this.

**Comment by 1egoman** [comment]
@radrad That was a touch one, but I think I finally fixed this.

Let me answer a few of your questions above.

```
Should I use "Rebase and Merge" instead of "Create a merge commit" to accomplish clear history of upstream repository branch. I would like to have exactly the same history of commits (excluding merge commit. Is it possible).
```

I'm a little fuzzy on it myself, but I think `rebase and merge` would do what you're asking - Give it a try.

```
Can you paste here what you are getting in backstroke.us code behind when one sets
http://backstroke.us as the payload url on his forked repo and push event or everything.
```

Just logs, which on their own aren't really helpful without context. If you want to understand what's going on behind the scenes, here's a [great place to start](https://github.com/1egoman/backstroke/blob/master/src/controllers/webhookOld.js), though keep in mind that this code is pretty worse-for-ware at this point.
```
$ npm start
> backstroke@2.0.0 start /Users/ryan/w/1egoman/backstroke
> NODE_PATH=src/ babel-node src/server.js
Listening on port 8000 ...
Merging upstream 1egoman/bluebird
Making pull to 1egoman bluebird
```

As far as seeing the webhook request and response, you can click on the blue uuid on github's webhook settings for a repository to see more details, including request headers / body and response headers / body.

```
What response are you suppose to send to github? Any required response? And are you making a synchronous call to github POST /repos/:owner/:repo/pulls to create a pull request.
```

Yep, that's the endpoint I'm using to make a pull request. I'm not asserting anything against the response other than its a 200-class status code. [Here's where the call is made](https://github.com/1egoman/backstroke/blob/master/src/controllers/webhookOld.js#L117-L123)

```
Is there a way to do "Create a merge commit" via rest api afterwords avoiding manual merge?
```
Yes, looks like there's an endpoint for it: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button


(The below is more for my own records, but if you're interested in what happened, read on)

Github's `POST /repos/:owner/:repo/pulls` endpoint added a parameter in the body called `maintainer_can_modify`. By default, it's set to true, and this mean't that if you didn't own both repositories that were being PRed against, the call would fail, because you don't have permission to grant editing privileges on the upstream repository.

Wouldn't normally be a problem (just update the api call), but `node-github` (the github library I'm using) hadn't updated to support that flag yet. I proposed a change to that project and got the dependency updated to support the new flag. Once this was done, I updated all my api calls, made a few compatibility changes (the new version of `node-github` changed a few things), pushed up my code, and it worked!

**Comment by radrad** [comment]
Great,. I will check it. This "Merge a pull request (Merge Button)" with its PUT /repos/:owner/:repo/pulls/:number/merge method is the right method to call after the PR has been created.
Is there a way you can provide an endpoint or extra query parameter where one can add merge_method = merge, squash or rebase and call this method. This will solve my problem. You just need to provide Accep headert: application/vnd.github.polaris-preview+json since this is in preview. this way others won't be affected if they don't provide this query parameter.
BTW what is sha input parameter in merge method: "SHA that pull request head must match to allow merge" Does it mean if we have multiple PRs created that we need to pick up one we want to merge from.
Also I want to know since "Every pull request is an issue" will it be opened and closed after calling pulls and merge method in sequence.

Do you know of a way to do debugging of node.js server code on windows. I would like to see what is going on in your code while the hook call is being made. I have Visual Studio 2015 and Visual Studio Code.

So it would be great if you could implement merge api call with those 3 variants so I don't have to write my own hook.

I tested your new hook and I don't know why it doesn't work. You can see my comments in the picture
[Web hook doesn't work](https://drive.google.com/file/d/0B1I1nQTGClv3WWtrbnhNanE3a3M/view?usp=sharing)

This picture: [Manual Pull Request and Merge and Rebase](https://drive.google.com/file/d/0B1I1nQTGClv3MTJVU1VUNVpacms/view?usp=sharing)
shows that there are some commits in the original https://github.com/radrad1/DevOpsWorkRadGit that PR can be created for. 
What am I missing here?

**Comment by radrad** [comment]
I actually tried creating a webhook receiver implemented by Microsoft.AspNet.WebHooks.Receivers.GitHub
which check for valid secret key and if the github post message for events is signed by they key. 
As I said above on the forked repo I only get a Ping event sent to my webhook receiver. Only if I am the owner of the source repo (I tried that as well) I will receive all events I subscribe too. 
So are you really sure you a getting event notifications when the original source repo is being updated (ping, push, issue opened, closed etc.).

**Comment by radrad1** [comment]
I tested your new code and a successful pull request created 
I could see 2 pull requests being created
Update from upstream repo radrad1/DevOpsWorkRadGit
#4 by backstroke-bot was merged 8 minutes ago  
 Update from upstream repo radrad1/DevOpsWorkRadGit
#3 by backstroke-bot was merged 10 minutes ago  

but I could see 3 Post messages being delivered.
1st. Ping >>> Success!
2n'd Push >>>> Success!  (Probably when #3 pull request was created (I already had 2 manual ones created)
and 
3rd. also Push, but with this error:
Uhh, error : {
	"message" : "Validation Failed",
	"errors" : [{
			"resource" : "PullRequest",
			"code" : "custom",
			"message" : "No commits between radrad:master and radrad1:master"
		}
	],
	"documentation_url" : "https://developer.github.com/v3/pulls/#create-a-pull-request"
}

After this error is reported no more Pushes were detected. 
Do you have some state that you mainatin in case something wrong is going on.
I already sent you my email if you want to meet in an online session to try to debug this issue.

Rad

**Comment by 1egoman** [comment]
I think I fixed your issue (you seem to have gotten two PRs), so I'm going to close this issue. If you see any more problems with Backstroke feel free to open another issue.

**Comment by radrad** [comment]
It is not fixed fully. I am not receiving any other pull requests after initial 2. It seems when the second one is created there is an error and after that it won't create any. Please keep this opened. Did you read my questions above? Thanks

**Comment by 1egoman** [comment]
I think what you saw is expected. Basically, both branches have the same HEAD commit, which means that there are no differences between the branches. Github won't let you create a pull request between two branches that point to the same commit.
